[workspace]
authors = ["mori5600 <211203777+mori5600@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "scoop-gui"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
app = "python -m app.main"
designer = "pyside6-designer"
uic-all = "powershell -NoProfile -ExecutionPolicy Bypass -File pwsh/ui2py.ps1"
check = "powershell -NoProfile -ExecutionPolicy Bypass -File pwsh/check.ps1"
format = "powershell -NoProfile -ExecutionPolicy Bypass -File pwsh/format.ps1"
build = "powershell -NoProfile -ExecutionPolicy Bypass -File pwsh/build.ps1"

[dependencies]
python = "3.12.*"
ruff = "==0.14.14"
ty = "==0.0.14"
nuitka = "==2.8.10"

[pypi-dependencies]
pyside6 = { version = "==6.10.1" }
